apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-app
spec:
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 5000       
      targetPort: 5000 
  selector:
    app: auth-app